name: CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.event_name != 'schedule' && github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      # 1) 저장소 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: 144.24.85.101 # 예: 144.24.85.101
          username: ubuntu # 서버 접속 유저명
          key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH 개인키 (GitHub Secrets)
          port: 22
          source: "." # 전체 파일(숨김 제외)
          target: "/home/web" # 서버의 배포 디렉터리
          overwrite: true # 같은 파일은 덮어쓰기

  backup:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Fetch code from server
        run: |
          rsync -avz \
            --exclude='_PHPExcel/' \
            -e "ssh -o StrictHostKeyChecking=yes" \
            ubuntu@${{ secrets.SERVER_HOST }}:/home/web/ \
            ./

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "${{ secrets.GIT_USER_NAME }}"
            git config user.email "${{ secrets.GIT_USER_EMAIL }}"
            git add -A
            git commit -m "Auto backup from server: $(date '+%F %T')"
            git push origin main
          else
            echo "No changes to commit."
          fi
